throwErrorOnExtraParameters: true
defaultToSvg: true

templates:
  A4 portrait JSON demo: !template
    reportTemplate: json_demo_main.jrxml
    attributes:
      additional_information_json: !string {}
    processors:
      - !reportBuilder
        directory: '.'
